### ISSUE TITLE
[iOS] VideoView can't display video

### ISSUE THREAD

**Issue by geektop** [rretamal/MauiVLC#3]
When running on iOS devices, control area is blank and the video cannot be displayed. But the sound of the video can be heard.
![jpg1](https://github.com/rretamal/MauiVLC/assets/30852915/fe3d63ee-db02-4890-89f1-c2a78b78f462)

**Comment by drowe5** [comment]
@geektop I'm experiencing this same issue on iOS. It plays the sound but no video plays. The logs are filled with: 

[h264 @ 0x7f8931536800] get_buffer() failed
[h264 @ 0x7f8931536800] thread_get_buffer() failed
[h264 @ 0x7f8931536800] decode_slice_header error
[h264 @ 0x7f8931536800] no frame!

I see that you closed this Issue. How did you fix it to get video to play on iOS?

**Comment by m-kojic** [comment]
I released a PR for the fix. The problem is that the control didn't have sufficient size to render the player so I set the width for the control along with height and the problem was resolved.
